### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by Oxyd76** [RoadWorksSoftware/eyecu-qt#1]
Ошибка в обработчике XHTML. В ссылке вида:
```html
<a href="https://scontent-ams3-1.xx.fbcdn.net/hphotos-xat1/t31.0-8/12694692_914105462037602_2700437260408561431_o.jpg">https://scontent-ams3-1.xx.fbcdn.net/hph...05462037602_2700437260408561431_o.jpg</a>
```
вместо перехода по `<a href="link">` происходит переход по описанию, находящемуся между `<a>bad_link</a>`

**Comment by yagiza** [comment]
Fixed in commit 911dd288c4f8134af0f0362cf449c4533ee76a00
