### ISSUE TITLE
Сделать кнопку "Показать личные данные" при нажатии на аватар пользователя, справа, вверху, в окне сообщений

### ISSUE THREAD

**Issue by opiums9** [RoadWorksSoftware/eyecu-qt#15]
Уже есть возможность вызывать контекстное меню контакта при нажатии ПКМ на аватар пользователя, хотелось бы при нажатии на ЛКМ вызывать функцию "показать личные данные"

**Comment by yagiza** [comment]
Зачем это нужно, если на тулбаре и так есть кнопка показа визитки?
