### ISSUE TITLE
Не работает контекстное меню при включённой лупе на карте

### ISSUE THREAD

**Issue by opiums9** [RoadWorksSoftware/eyecu-qt#16]
При использовании лупы на карте, если не знаешь что она отключается на F8 невозможно отключить её используя другие клавиши

**Comment by yagiza** [comment]
По ПКМ всплывает контекстное меню, из которого её можно отключить!

**Comment by yagiza** [comment]
Походу, контекстное пеню при включённой лупе поломалось! Открываю тикет заново!

**Comment by yagiza** [comment]
Fixed in version 1.3.0.20170511
