### ISSUE TITLE
Кнопка в окне сообщения настройки

### ISSUE THREAD

**Issue by opiums9** [RoadWorksSoftware/eyecu-qt#18]
Очень удобно переходить в настройки прямо из окна сообщения

**Comment by yagiza** [comment]
Необходимость вызывать настройки очень редкая. Обычно человек настраивает клиент под себя один раз и потом заходит в настройки очень редко. Заходить туда каждые 5 минут нет никакой необходимости. Поэтому не вижу смысла засорять тулбар чата лишней кнопкой. Он и так, несколько перегружен.
