### ISSUE TITLE
Разделение ярлыков x32 и x64 версий

### ISSUE THREAD

**Issue by opiums9** [RoadWorksSoftware/eyecu-qt#2]
Хорошо было бы разделить ярлыки по названию и сделать eyeCU x64 и Maintain eyeCU x64

**Comment by yagiza** [comment]
Обычно люди пользуются только одной версией программы: либо x32, либо x64. И дополнительный текст в названии ярлыка им будет только мешать. В тех редких случаях, когда им нужно установить 2 версии одновременно, он может легко положить иконки в разные папки и запускать оттуда. А если путается - руками переименовать ярлыки.
