### ISSUE TITLE
Возможность изменения звуковых оповещений на свои

### ISSUE THREAD

**Issue by opiums9** [RoadWorksSoftware/eyecu-qt#27]
Хотелось бы внедрять свои звуковые схемы, звуки, мелодии вместо стандартных

**Comment by yagiza** [comment]
Ну, никто не мешает подготовить свою "схему" и скопировать в resources/sounds.

**Comment by yagiza** [comment]
Автор тикета ничего не ответил на мой комментарий. Закрываю.
