### ISSUE TITLE
Файлы с настройками

### ISSUE THREAD

**Issue by opiums9** [RoadWorksSoftware/eyecu-qt#28]
Хотелось бы иметь экспорт/импорт файла с настройками для быстрого переноса настроек (только настроек) на другой компьютер. Или же хранить настройки на удалённом сервере, чтобы производить синхронизацию с ними.

**Comment by yagiza** [comment]
А кто мешает просто скопировать options.xml из своего профиля?

**Comment by yagiza** [comment]
Поскольку ответа от автора тикета так и не поступило, закрываю его.
